# -*- coding: utf-8 -*-
"""
plot_horizon_curves.py
=========================
Reads data/horizon_regret_diff.csv and data/horizon_radius_ratio.csv
(generated by gen_horizon_data.py) and produces figures/horizon_scaling.pdf.
Does NOT run any bandit -- plotting only.

Run:
    python plot_horizon_curves.py
"""
import csv

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

IN_DIFF_CSV = "../data/horizon_regret_diff.csv"
IN_RATIO_CSV = "../data/horizon_radius_ratio.csv"
OUT_PDF = "../figures/horizon_scaling.pdf"

COL_DIFF = "tab:purple"
COL_RATIO = "tab:brown"
HORIZONS = (10**4, 10**5, 10**6, 10**7)
BETA = 1.25                       # beta used in the experiment (gen_horizon_data.py)
ASYMPTOTE = np.sqrt(2.0) / BETA   # eps_KL/eps_F ratio of the OPTIMAL arm -> sqrt(2)/beta (=1 iff beta=sqrt2)


def load(path, ycol):
    x, y = [], []
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            x.append(int(row["round"]))
            y.append(float(row[ycol]))
    return x, y


def main():
    x_diff, y_diff = load(IN_DIFF_CSV, "regret_diff")
    x_ratio, y_ratio = load(IN_RATIO_CSV, "radius_ratio")

    fig, ax = plt.subplots(1, 2, figsize=(12, 4))

    ax[0].plot(x_diff, y_diff, color=COL_DIFF, lw=2, label="Fisher-UCB - KL-UCB")
    ax[0].axhline(0, color='black', ls='--', alpha=0.5)
    for cp in HORIZONS:
        ax[0].axvline(cp, color='gray', ls=':', alpha=0.3)
    ax[0].set_title("Regret Difference Over Time", fontsize=10)
    ax[0].set_xlabel("Round t (log scale)"); ax[0].set_ylabel("Regret Difference")
    ax[0].set_xscale("log"); ax[0].legend(fontsize=9)
    ax[0].grid(True, which="both", ls="--", alpha=0.3)

    ax[1].plot(x_ratio, y_ratio, color=COL_RATIO, lw=2, label=r"Ratio ($\epsilon^{KL}_t / \epsilon^{F}_t$)")
    ax[1].axhline(ASYMPTOTE, color='black', ls='--', alpha=0.8,
                  label=r"$\sqrt{2}/\beta \approx %.2f$ (asymptote)" % ASYMPTOTE)
    ax[1].axhline(1.0, color='gray', ls=':', alpha=0.6, label=r"$1$ (only if $\beta=\sqrt{2}$)")
    for cp in HORIZONS:
        ax[1].axvline(cp, color='gray', ls=':', alpha=0.3)
    ax[1].set_title("Radius Ratio (Optimal Arm)", fontsize=10)
    ax[1].set_xlabel("Round t (log scale)"); ax[1].set_ylabel("Radius Ratio")
    ax[1].set_xscale("log"); ax[1].legend(fontsize=9)
    ax[1].grid(True, which="both", ls="--", alpha=0.3)

    plt.tight_layout()
    plt.savefig(OUT_PDF)
    print(f"{OUT_PDF} generated (from the CSVs, no re-simulation).")


if __name__ == "__main__":
    main()
