# -*- coding: utf-8 -*-
"""
plot_binomial_curves.py
=========================
Reads a binomial_curves CSV (generated by gen_binomial_data.py; default
data/binomial_curves.csv, pass in_csv= for the paper's 100-seed replication)
and produces a PDF (default figures/binomial_curves.pdf; pass out_pdf=
accordingly) -- Figure 3: sign reversal. Does NOT run any bandit -- plotting
only.

Run:
    python plot_binomial_curves.py
"""
import csv
from collections import defaultdict

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

IN_CSV = "../data/binomial_curves.csv"
OUT_PDF = "../figures/binomial_curves.pdf"

COL = {"UCB1": "tab:blue", "KL-UCB": "tab:orange", "Fisher-UCB": "tab:green"}
STY = {"UCB1": "-.", "KL-UCB": "--", "Fisher-UCB": "-"}
TITLES = {"favorable": "Binomial favorable (rho<0, p<1/2)",
          "adverse": "Binomial adverse (rho>0, p>1/2)"}


def load(path):
    data = defaultdict(lambda: {"round": [], "mean": [], "std": []})
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            key = (row["panel"], row["algorithm"])
            d = data[key]
            d["round"].append(int(row["round"]))
            d["mean"].append(float(row["mean_regret"]))
            d["std"].append(float(row["std_regret"]))
    return data


def main(in_csv=IN_CSV, out_pdf=OUT_PDF):
    data = load(in_csv)
    fig, ax = plt.subplots(1, 2, figsize=(11, 4))

    for i, panel in enumerate(["favorable", "adverse"]):
        for name in ("UCB1", "KL-UCB", "Fisher-UCB"):
            d = data[(panel, name)]
            x, m, sd = d["round"], d["mean"], d["std"]
            lo = [max(mi - si, 0) for mi, si in zip(m, sd)]
            hi = [mi + si for mi, si in zip(m, sd)]
            ax[i].plot(x, m, STY[name], color=COL[name], label=name, lw=1.5)
            ax[i].fill_between(x, lo, hi, color=COL[name], alpha=0.15)
        ax[i].set_title(TITLES[panel], fontsize=10)
        ax[i].set_xlabel("round t"); ax[i].set_ylabel("cumulative regret"); ax[i].legend(fontsize=8)

    plt.tight_layout()
    plt.savefig(out_pdf)
    print(f"{out_pdf} generated (from {in_csv}, no re-simulation).")


if __name__ == "__main__":
    main()
