# -*- coding: utf-8 -*-
"""
plot_poisson_curves.py
========================
Reads a poisson_curves CSV (generated by gen_poisson_data.py; default
data/poisson_curves.csv, pass in_csv= for the paper's higher-seed
replication) and produces a PDF (default figures/poisson_curves.pdf; pass
out_pdf= accordingly). Does NOT run any bandit -- plotting only.

Panel 1 (small_gaps): mean +- 1 std, like the other regret figures.
Panel 2 (projection_ablation): mean + band up to the P95 (the projection
effect is a TAIL effect, invisible in a +-1 std band with few seeds).

Run:
    python plot_poisson_curves.py
"""
import csv
from collections import defaultdict

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

IN_CSV = "../data/poisson_curves.csv"
OUT_PDF = "../figures/poisson_curves.pdf"

COL = {"UCB1": "tab:blue", "KL-UCB": "tab:orange", "Fisher-UCB": "tab:green",
       "Fisher-UCB (proj)": "tab:green", "Fisher-UCB (no proj)": "tab:red"}
STY = {"UCB1": "-.", "KL-UCB": "--", "Fisher-UCB": "-",
       "Fisher-UCB (proj)": "-", "Fisher-UCB (no proj)": ":"}


def load(path):
    data = defaultdict(lambda: {"round": [], "mean": [], "std": [], "p95": [], "max": None})
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            key = (row["panel"], row["algorithm"])
            d = data[key]
            d["round"].append(int(row["round"]))
            d["mean"].append(float(row["mean_regret"]))
            d["std"].append(float(row["std_regret"]))
            d["p95"].append(float(row["p95_regret"]))
            d["max"] = float(row["max_final_regret"])
    return data


def main(in_csv=IN_CSV, out_pdf=OUT_PDF):
    data = load(in_csv)
    fig, ax = plt.subplots(1, 2, figsize=(11, 4))

    # panel 1: small_gaps, mean +- 1 std
    for name in ("UCB1", "KL-UCB", "Fisher-UCB"):
        d = data[("small_gaps", name)]
        x, m, sd = d["round"], d["mean"], d["std"]
        lo = [max(mi - si, 0) for mi, si in zip(m, sd)]
        hi = [mi + si for mi, si in zip(m, sd)]
        ax[0].plot(x, m, STY[name], color=COL[name], label=name, lw=1.5)
        ax[0].fill_between(x, lo, hi, color=COL[name], alpha=0.15)
    ax[0].set_title("Poisson, small gaps (best=2.2, gaps 0.1-0.3)", fontsize=10)
    ax[0].set_xlabel("round t"); ax[0].set_ylabel("cumulative regret"); ax[0].legend(fontsize=8)

    # panel 2: projection_ablation, mean + band up to P95, max in the label
    for name in ("Fisher-UCB (proj)", "Fisher-UCB (no proj)"):
        d = data[("projection_ablation", name)]
        x, m, p95, mx = d["round"], d["mean"], d["p95"], d["max"]
        lbl = f"{name}: mean {m[-1]:.0f}, max {mx:.0f}"
        ax[1].plot(x, m, STY[name], color=COL[name], lw=1.8, label=lbl)
        ax[1].fill_between(x, m, p95, color=COL[name], alpha=0.18)
    ax[1].set_title("Poisson near zero (best=0.20): role of projection", fontsize=10)
    ax[1].set_xlabel("round t"); ax[1].set_ylabel("cumulative regret")
    ax[1].legend(fontsize=8, loc="upper left")

    plt.tight_layout()
    plt.savefig(out_pdf)
    print(f"{out_pdf} generated (from {in_csv}, no re-simulation).")


if __name__ == "__main__":
    main()
