# -*- coding: utf-8 -*-
"""
plot_regret_curves.py
======================
Reads data/regret_curves.csv (generated by gen_regret_data.py) and produces
figures/regret_curves.pdf (Figure 1 of the paper). Does NOT run any bandit --
plotting only. Edit colors/styles/titles here freely, with no re-simulation.

Run:
    python plot_regret_curves.py
"""
import csv
from collections import defaultdict

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

IN_CSV = "../data/regret_curves.csv"
OUT_PDF = "../figures/regret_curves.pdf"

COL = {"UCB1": "tab:blue", "KL-UCB": "tab:orange", "Fisher-UCB": "tab:green"}
STY = {"UCB1": "-.", "KL-UCB": "--", "Fisher-UCB": "-"}


def load(path):
    """Returns dict[(panel, algorithm)] -> dict with lists 'round','mean','std'."""
    data = defaultdict(lambda: {"round": [], "mean": [], "std": []})
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            key = (row["panel"], row["algorithm"])
            d = data[key]
            d["round"].append(int(row["round"]))
            d["mean"].append(float(row["mean_regret"]))
            d["std"].append(float(row["std_regret"]))
    return data


def main():
    data = load(IN_CSV)
    panels = sorted({k[0] for k in data})
    fig, ax = plt.subplots(1, len(panels), figsize=(5.5 * len(panels), 4))
    if len(panels) == 1:
        ax = [ax]

    for i, panel in enumerate(panels):
        for name in ("UCB1", "KL-UCB", "Fisher-UCB"):
            d = data[(panel, name)]
            x, m, sd = d["round"], d["mean"], d["std"]
            lo = [max(mi - si, 0) for mi, si in zip(m, sd)]
            hi = [mi + si for mi, si in zip(m, sd)]
            ax[i].plot(x, m, STY[name], color=COL[name], label=name, lw=1.5)
            ax[i].fill_between(x, lo, hi, color=COL[name], alpha=0.15)
        ax[i].set_title(panel, fontsize=10)
        ax[i].set_xlabel("round t")
        ax[i].set_ylabel("cumulative regret")
        ax[i].legend(fontsize=8)

    plt.tight_layout()
    plt.savefig(OUT_PDF)
    print(f"{OUT_PDF} generated (from {IN_CSV}, no re-simulation).")


if __name__ == "__main__":
    main()
