# -*- coding: utf-8 -*-
"""
plot_arms_scaling_curves.py
==============================
Reads data/arms_scaling_runtime.csv and data/arms_scaling_regret_k100.csv
(generated by gen_arms_scaling_data.py) and produces two figures:
  figures/scaling_runtime.pdf      : runtime vs K, log-log, Bern+Exp.
  figures/scaling_regret_k100.pdf  : regret trajectories at K=100 (a
                                      diagnostic check; not included in the
                                      paper -- reproduce_paper.py only calls
                                      plot_runtime()).
Does NOT run any bandit -- plotting only.

Run:
    python plot_arms_scaling_curves.py
"""
import csv
from collections import defaultdict

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

IN_RUNTIME_CSV = "../data/arms_scaling_runtime.csv"
IN_REGRET_CSV = "../data/arms_scaling_regret_k100.csv"
OUT_RUNTIME_PDF = "../figures/scaling_runtime.pdf"
OUT_REGRET_PDF = "../figures/scaling_regret_k100.pdf"

COL = {"UCB1": "tab:blue", "KL-UCB": "tab:orange", "Fisher-UCB": "tab:green"}
STY = {"UCB1": "-.", "KL-UCB": "--", "Fisher-UCB": "-"}


def plot_runtime():
    data = defaultdict(lambda: defaultdict(dict))  # family -> algo -> {K: time}
    K_list = set()
    with open(IN_RUNTIME_CSV, newline="") as f:
        for row in csv.DictReader(f):
            K = int(row["K"]); K_list.add(K)
            data[row["family"]][row["algorithm"]][K] = float(row["runtime_mean"])
    K_list = sorted(K_list)

    families = sorted(data.keys())
    fig, ax = plt.subplots(1, len(families), figsize=(5.5 * len(families), 4))
    if len(families) == 1:
        ax = [ax]
    for i, family in enumerate(families):
        for name in ("UCB1", "KL-UCB", "Fisher-UCB"):
            times = [data[family][name][K] for K in K_list]
            ax[i].plot(K_list, times, marker='o', ls=STY[name], color=COL[name], label=name, lw=1.5)
        ax[i].set_title(f"{family} Runtime Scaling", fontsize=10)
        ax[i].set_xlabel("Number of Arms (K)")
        ax[i].set_ylabel("Total Runtime (seconds)")
        ax[i].set_xscale("log"); ax[i].set_yscale("log")
        ax[i].set_xticks(K_list)
        ax[i].get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
        ax[i].legend(fontsize=8)
        ax[i].grid(True, which="both", ls="--", alpha=0.5)
    plt.tight_layout()
    plt.savefig(OUT_RUNTIME_PDF)
    print(f"{OUT_RUNTIME_PDF} generated.")


def plot_regret_k100():
    data = defaultdict(lambda: {"round": [], "mean": [], "std": []})
    with open(IN_REGRET_CSV, newline="") as f:
        for row in csv.DictReader(f):
            key = (row["panel"], row["algorithm"])
            d = data[key]
            d["round"].append(int(row["round"]))
            d["mean"].append(float(row["mean_regret"]))
            d["std"].append(float(row["std_regret"]))

    families = sorted({k[0] for k in data})
    fig, ax = plt.subplots(1, len(families), figsize=(5.5 * len(families), 4))
    if len(families) == 1:
        ax = [ax]
    for i, family in enumerate(families):
        for name in ("UCB1", "KL-UCB", "Fisher-UCB"):
            d = data[(family, name)]
            x, m, sd = d["round"], d["mean"], d["std"]
            lo = [max(mi - si, 0) for mi, si in zip(m, sd)]
            hi = [mi + si for mi, si in zip(m, sd)]
            ax[i].plot(x, m, STY[name], color=COL[name], label=name, lw=1.5)
            ax[i].fill_between(x, lo, hi, color=COL[name], alpha=0.15)
        ax[i].set_title(f"{family} (K=100)", fontsize=10)
        ax[i].set_xlabel("round t"); ax[i].set_ylabel("cumulative regret"); ax[i].legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(OUT_REGRET_PDF)
    print(f"{OUT_REGRET_PDF} generated.")


def main():
    plot_runtime()
    plot_regret_k100()


if __name__ == "__main__":
    main()
